---
title: "Day 4 Homework"
output: html_document
---

1. Find some aspect of your data that needs to be combined or merged in some way.  This could be a variety of things:
  - multiple "sheets" in an Excel
  - multiple files that should be combined into one data set
  - properties that need to be merged in to one data set. For example:
    - you have a table of subject properties (gender, handedness, etc.) that need to be merged into the item-level data
    - you have other information on countries (population, etc.) that need to be merged in
  - if you DON'T have this naturally-occurring issue, figure out a way to manufacture it. For example:
    - split up your data into chunks
    - make up some new table of information that you want to merge in
  - Explain (in words) what you are trying to do
  - Use binding/merging commands to accomplish this
  - Complete at least ONE example of binding and ONE example of merging

```{r}
library(dplyr)
scottdata <- read.csv("scottdata/CognitionPaperFinalData.csv")

lang.family <- data.frame(Language = c("American English", "British English", "German", "Dutch",
                                     "Spanish", "French", "Italian", "Portuguese",
                                     "Slovakian", "Russian", "Czech",
                                     "Cantonese", "Mandarin",
                                     "Korean"),
                        Family = c(rep("Germanic", 4),
                                   rep("Romance", 4),
                                   rep("Slavic", 3),
                                   rep("Sino-Tibetan", 2),
                                   "Koreanic"))
                        
levels(scottdata$Corpus)
levels(lang.family$Language)

scottdata$Language <- scottdata$Corpus
levels(scottdata$Language)
levels(scottdata$Language) <- c("American English", "Dutch", "French", "German", "Cantonese", "Korean", "British English", "Slovakian", "Spanish")
scottdata$Language <- factor(scottdata$Language, levels = levels(lang.family$Language))
xtabs(~ Language + Corpus, scottdata)

scottdata.merged <- left_join(scottdata, lang.family, by = "Language")

nrow(scottdata)
nrow(scottdata.merged)

xtabs(~ Language + Family, scottdata.merged)

```
